# Generated by Django 3.1.5 on 2021-01-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBinfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField(null=True, verbose_name='なんかのURL')),
                ('email', models.EmailField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
